/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.b68103.vista;

import javax.swing.JOptionPane;
import ucr.ac.cr.b68103.controlador.ManejadorEstudiante;
import ucr.ac.cr.b68103.modelo.RegistroEstudiante;

/**
 *
 * @author coordinacion
 */
public class FrmEstudiante extends javax.swing.JFrame {
ManejadorEstudiante manejador;
    /**
     * Creates new form FrmEstudiante
     */
    public FrmEstudiante(RegistroEstudiante registroEstudiante) {
        initComponents();
        manejador=new ManejadorEstudiante(pnlDatosEstudiante1,pnlBotones1,this,registroEstudiante);
        pnlBotones1.escuchar(manejador);
        pnlDatosEstudiante1.escuchar(manejador);
         setLocationRelativeTo(null);
    }
    public void msj(String msj){
        JOptionPane.showMessageDialog(this,msj);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosEstudiante1 = new ucr.ac.cr.b68103.vista.PnlDatosEstudiante();
        pnlBotones1 = new ucr.ac.cr.b68103.vista.PnlBotones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlDatosEstudiante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, -1));
        getContentPane().add(pnlBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.b68103.vista.PnlBotones pnlBotones1;
    private ucr.ac.cr.b68103.vista.PnlDatosEstudiante pnlDatosEstudiante1;
    // End of variables declaration//GEN-END:variables
}
