/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.b68103.vista;

import javax.swing.JOptionPane;
import ucr.ac.cr.b68103.controlador.ManejadorLibro;
import ucr.ac.cr.b68103.modelo.RegistroLibro;

/**
 *
 * @author Usuario
 */
public class FrmLibro extends javax.swing.JFrame {

    /**
     * Creates new form FrmLibro
     */
    public FrmLibro(RegistroLibro registroLibro) {
        initComponents();
        ManejadorLibro manejadorLibro;
        manejadorLibro = new ManejadorLibro(pnlDatosLibro1,pnlLibroBotones1,this,registroLibro);
        this.pnlLibroBotones1.escuchar(manejadorLibro);
        this.pnlDatosLibro1.escuchar(manejadorLibro);
    }
    
    
    
    public static void getMensaje(String smj){
        JOptionPane.showMessageDialog(null,smj);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosLibro1 = new ucr.ac.cr.b68103.vista.PnlDatosLibro();
        pnlLibroBotones1 = new ucr.ac.cr.b68103.vista.PnlLibroBotones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlDatosLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 440, 270));

        pnlLibroBotones1.setBackground(new java.awt.Color(0, 204, 153));
        getContentPane().add(pnlLibroBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 460, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.b68103.vista.PnlDatosLibro pnlDatosLibro1;
    private ucr.ac.cr.b68103.vista.PnlLibroBotones pnlLibroBotones1;
    // End of variables declaration//GEN-END:variables
}
