/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.b68103.vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import ucr.ac.cr.b68103.controlador.ManejadorPrestamo;
import ucr.ac.cr.b68103.modelo.RegistroPrestamo;

/**
 *
 * @author Usuario
 */
public class FrmPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrestamo
     */
    public FrmPrestamo(RegistroPrestamo registroPrestamo) {
        initComponents();
         ManejadorPrestamo prestamo= new ManejadorPrestamo(pnlDatosPrestamo1,pnlBotonesPrestamo1,pnlTablaPrestamo1,this,registroPrestamo);
        this.pnlBotonesPrestamo1.escuchar(prestamo);
        this.pnlDatosPrestamo1.escuchar(prestamo);
       
       
        
        
        setLocationRelativeTo(null);
    }
     public static void getMensaje(String smj){
        JOptionPane.showMessageDialog(null,smj);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosPrestamo1 = new ucr.ac.cr.b68103.vista.PnlDatosPrestamo();
        pnlTablaPrestamo1 = new ucr.ac.cr.b68103.vista.PnlTablaPrestamo();
        pnlBotonesPrestamo1 = new ucr.ac.cr.b68103.vista.PnlBotonesPrestamo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlDatosPrestamo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(pnlTablaPrestamo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 271, 626, 180));
        getContentPane().add(pnlBotonesPrestamo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 457, 606, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.b68103.vista.PnlBotonesPrestamo pnlBotonesPrestamo1;
    private ucr.ac.cr.b68103.vista.PnlDatosPrestamo pnlDatosPrestamo1;
    private ucr.ac.cr.b68103.vista.PnlTablaPrestamo pnlTablaPrestamo1;
    // End of variables declaration//GEN-END:variables
}
