/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.b68103.vista;

import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import ucr.ac.cr.b68103.controlador.ManejadorPrestamo;
import ucr.ac.cr.b68103.modelo.RegistroLibro;
import ucr.ac.cr.b68103.modelo.RegistroPrestamo;

/**
 *
 * @author Usuario
 */
public class PnlDatosPrestamo extends javax.swing.JPanel {

    RegistroLibro registroLibro = new RegistroLibro();
    String vectorSignatura[];
    DefaultComboBoxModel modelSignatura;

    /**
     * Creates new form PnlDatosPrestamo
     */
    public PnlDatosPrestamo() {
        initComponents();

        Calendar calendar = Calendar.getInstance();
        String fecha;
        fecha = calendar.get(Calendar.DATE) + "/" + calendar.get(Calendar.MONTH) + "/" + calendar.get(Calendar.YEAR);
        this.jlbFecha.setText(fecha);
        this.vectorSignatura = new String[registroLibro.contador()];
        cargarCombobox();

    }

    public String getTxtCarnet() {
        return txtCarnet.getText().toString().trim();
    }

    public void setTxtCarnet(String carnet) {
        this.txtCarnet.setText(carnet);
    }

    public Date getSpFechaDevolucion() {
        return (Date) this.jspFechaDevolucion.getModel().getValue();
    }

    public void setSpFechaDevolucion(Date fecha) {
        this.jspFechaDevolucion.getModel().setValue(fecha);
    }

    public String getCeboxLibros() {
        return (String) this.jcboxLibro.getModel().getSelectedItem();
    }

    /**
     *
     * @param signatura
     */
    //set  y get
    public void setCboxLibros(String signatura) {
        this.jcboxLibro.getModel().setSelectedItem(signatura);
    }

    public String getLblNombre() {
        return this.jlblNombre.getText();
    }

    public void setLblNombre(String nombre) {
        this.jlblNombre.setText(nombre);
    }

    public String getlblFecha() {
        return this.jlbFecha.getText();
    }

    public void setLblFecha(String fecha) {
        this.jlbFecha.setText(fecha);
    }

    public String getLblID() {
        return this.lblID.getText();
    }

    public void setLblID(String codigo) {
        this.lblID.setText(codigo);
    }

    //fin de set y get
    //llenar vector
    public void llenarVector() {
        this.vectorSignatura[0] = "Seleccione un libro";
        for (int i = 1; i <= this.vectorSignatura.length; i++) {
            this.vectorSignatura[i] = registroLibro.getLibro(i - 1).getSignatura();
        }

    }

    //cargar combobox libros
    public void cargarCombobox() {
        this.modelSignatura = new DefaultComboBoxModel(vectorSignatura);
        jcboxLibro.setModel(modelSignatura);
    }
    //fin del metodo cargar

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblPrestamoLibros = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcboxLibro = new javax.swing.JComboBox<>();
        btnAgregarLibro = new javax.swing.JButton();
        btnPrestamo = new javax.swing.JButton();
        jlbFecha = new javax.swing.JLabel();
        jspFechaDevolucion = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPrestamoLibros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrestamoLibros.setText("Prestamo de Libros");

        lblCod.setText("COD:");

        jLabel1.setText("Fecha de prestamo :");

        jLabel3.setText("Fecha de Devolución:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Seleccione los libros que decea solicitar");

        btnAgregarLibro.setText("Agregar Libro");

        btnPrestamo.setText("Prestamo");

        jlbFecha.setText(" ");

        jspFechaDevolucion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(1565197800000L), java.util.Calendar.DAY_OF_WEEK_IN_MONTH));

        jLabel5.setText("Carnet:");

        txtCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarnetActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");

        jLabel6.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrestamoLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268)
                        .addComponent(lblCod)
                        .addGap(18, 18, 18)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jcboxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarLibro)
                        .addGap(304, 304, 304))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jlbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPrestamo)
                                    .addComponent(jspFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jlblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblPrestamoLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCod))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jlblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbFecha)
                        .addComponent(jLabel3)
                        .addComponent(jspFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcboxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarLibro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarnetActionPerformed

    /**
     *
     * @param control
     */
    public void escuchar(ActionListener control) {
        btnAgregarLibro.addActionListener(control);
        btnBuscar.addActionListener(control);
        btnPrestamo.addActionListener(control);
    }
    public static final String BTN_PRESTAMO = "Prestamo";
    public static final String BTN_BUSCAR = "buscar";
    public static final String BTN_AGREGAR = "Agregar Libro";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcboxLibro;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JSpinner jspFechaDevolucion;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPrestamoLibros;
    private javax.swing.JTextField txtCarnet;
    // End of variables declaration//GEN-END:variables

    
}
